
#import "@preview/mitex:0.2.4": *

// Setup fonts
#set text(font: "NanumGothic", lang: "ko")
#set page(paper: "a4", margin: 2cm)
#set par(justify: true)

// Load Data
// We use sys.inputs.data_file passed from the wrapper
#let data_file = sys.inputs.at("data_file", default: "school_data.json")
#let data = json(data_file)

// Header
#align(center)[
  #text(20pt, weight: "bold")[학교 분석 리포트 (School Analytics)]
  #v(1cm)
  #text(15pt)[#data.school_name]
]

#v(1cm)

// Basic Info Block
#block(stroke: black, inset: 10pt, radius: 5pt)[
  *기본 정보* \
  - 학교코드: #data.school_code \
  - 주소: #data.address \
  - 설립일자: #data.founding_date
]

#v(1cm)

// AI Summary
#heading(level: 1)[AI 요약 (AI Summary)]
#block(fill: luma(240), inset: 10pt, radius: 5pt)[
  #data.ai_summary
]

#v(1cm)

// Crawled Data Visualization
#heading(level: 1)[수집 데이터 (Crawled Data)]

*교육과정 (Curriculum)* \
#if data.curriculum.len() > 0 [
  #for curr in data.curriculum [
    - #curr.year #curr.grade 학년: #curr.subjects.map(s => s.name).join(", ")
  ]
] else [
  - 데이터 없음
]

#v(1cm)
#line(length: 100%)
#align(center)[Generated by Mathesis Engine]
